# Generated by Django 6.1.1 on 2026-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert_method',
            field=models.CharField(choices=[('VOICE', 'Voice Alert'), ('FLASHLIGHT', 'Flashlight'), ('BOTH', 'Both'), ('VIBRATION', 'Vibration Only')], default='VOICE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='alert_radius_m',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='user',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
