# Generated by Django 6.1.1 on 2026-09-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hazard_client_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='description_language',
            field=models.CharField(default='en-US', max_length=12),
        ),
        migrations.AddField(
            model_name='hazard',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
