# Generated by Django 6.1.1 on 2026-09-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alertlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('local_version', models.PositiveIntegerField(default=0)),
                ('server_version', models.PositiveIntegerField(default=0)),
                ('conflict_type', models.CharField(default='VERSION_MISMATCH', max_length=50)),
                ('local_payload', models.JSONField(blank=True, default=dict)),
                ('server_payload', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='UPDATE', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_seen_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='hazard-classifier', max_length=100)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('related_hazard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='core.hazard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
